rootDir: ./updaterroot
hubUrl: http://localhost:3000/updater

#How often the updater will poll for updates.
#Minimum 1 second, Maximum 24 hours (86400 seconds)
#Anything less than 1 second will be treated as 1 second.
#Anything greater than 24 hours will be treated as 24 hours.
#Anything invalid will be treated as 10 seconds.
updateIntervalSeconds: 5

deviceIdLength: 10

#If true, it will download but not actually execute the update script.
simulate: false

#If an update script takes longer than this, it will be interrupted.
#Max 1 hour, minimum 1 second.
#Default is 30 minutes. If any update takes longer than that, then something is DEFINITELY wrong!
updateScriptTimeoutSeconds: 1800

# Which port the display RPC server is listening on.
# https://github.com/sveasmart/display
# ... or leave it blank if we should just use console.log instead of trying to talk to a display
displayRpcPort: 5000

# If we fail to contact the display app, how often should we retry?
# 0 or blank means never.
displayResendIntervalSeconds: 10

# True if calls to the display should be logged
logDisplayCalls: false

# Which tab on the display that we use to write stuff
# (only relevant if displayRpcPort is given)
mainDisplayTab: "tab0"

# Which command should be executed when updaterHub says sshTunnelRequested: true
# If blank, it will be ignored.
sshTunnelCommand: ''

# If this is set, then the given script will be called when deviceId is set the first time.
# The deviceId itself will be sent as a parameter.
# For example, maybe we want to update the network name to match the deviceId.
scriptToCallWhenDeviceIdHasBeenSet: