rootDir: ./updaterroot
hubUrl: http://localhost:3000/updater

#How often the updater will poll for updates.
#Minimum 1 second, Maximum 24 hours (86400 seconds)
#Anything less than 1 second will be treated as 1 second.
#Anything greater than 24 hours will be treated as 24 hours.
#Anything invalid will be treated as 10 seconds.
updateIntervalSeconds: 5

deviceIdLength: 10

#If true, it will download but not actually execute the update script.
simulate: false

#If an update script takes longer than this, it will be interrupted.
#Max 1 hour, minimum 1 second.
#Default is 30 minutes. If any update takes longer than that, then something is DEFINITELY wrong!
updateScriptTimeoutSeconds: 1800


# Which port the display RPC server is listening on.
# https://github.com/sveasmart/display
displayRpcPort: 5000

# Which tab on the display that we use to write stuff.
mainDisplayTab: "tab0"

# Which tab on the display that we show network details
networkInfoDisplayTab: "tab1"